### ISSUE TITLE
Tests aren't designed to properly test PR changes when it would affect the Docker image

### ISSUE THREAD

**Issue by andy5995** [andy5995/gh-action-build-deb#8]
The CI needs a bit of changing to make it easier for PR submitters to test changes that would affect the docker image, such as the entrypoint.sh change proposed by @ehbello  in https://github.com/andy5995/gh-action-build-deb/pull/6

**Comment by andy5995** [comment]
@ehbello Do you have any feedback about https://github.com/andy5995/gh-action-build-deb/pull/9 before I merge it?

**Comment by ehbello** [comment]
> @ehbello Do you have any feedback about #9 before I merge it?

I replied there.
